# Generated by Django 4.0.5 on 2022-10-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Контакти'),
        ),
    ]
