# Generated by Django 4.0.5 on 2022-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_adv_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
