# Generated by Django 4.0.5 on 2022-10-25 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adv', '0003_adv_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvComent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('moderation', models.BooleanField(default=True, verbose_name='Модерация')),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coment_adv', to='adv.adv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комменты',
            },
        ),
    ]
