# Generated by Django 4.0.5 on 2022-09-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('icon', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('description', models.TextField(max_length=10000, verbose_name='Опис посуги')),
                ('images', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('location', models.CharField(max_length=20, verbose_name='Адреса')),
                ('name', models.CharField(max_length=50, verbose_name="Ваше ім'я")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='эл.почта')),
                ('telefon', models.CharField(blank=True, max_length=13, verbose_name='номер телефона')),
                ('moderation', models.BooleanField(default=True, verbose_name='Модерация')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.categoryservice', verbose_name='Категорія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Послга',
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
