# Generated by Django 4.0.5 on 2022-09-26 18:44

import autoslug.fields
from django.db import migrations
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_brend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from=service.models.instance_slug, slugify=service.models.slugify_value, unique=True, verbose_name='URL'),
        ),
    ]
