# Generated by Django 4.0.5 on 2022-10-06 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_alter_categoryservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryservice',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='service',
            name='brend',
            field=models.CharField(blank=True, max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.categoryservice', verbose_name='Категорія*'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Опис посуги*'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Адреса*'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ваше ім'я*"),
        ),
        migrations.AlterField(
            model_name='service',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Назва послуги*'),
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комменты',
            },
        ),
    ]
