# Generated by Django 4.0.5 on 2022-10-07 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_coment_serv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'verbose_name': 'Коммент', 'verbose_name_plural': 'Комменты'},
        ),
        migrations.AlterField(
            model_name='coment',
            name='moderation',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='serv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coment_service', to='service.service'),
        ),
    ]
