# Generated by Django 4.0.5 on 2022-10-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_coment_options_alter_coment_moderation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='serv',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='coment_service', to='service.service'),
            preserve_default=False,
        ),
    ]
