# Generated by Django 4.0.5 on 2022-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(default=1, max_length=20, verbose_name='Локація'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advert',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='moderation',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='types_ad',
            field=models.CharField(blank=True, choices=[('куплю', 'куплю'), ('продам', 'продам'), ('обміняю', 'обміняю'), ('віддам', 'віддам')], max_length=9, verbose_name='тип объявления'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='types_pr',
            field=models.CharField(blank=True, choices=[('нове', 'нове'), ('подержане', 'подержане')], max_length=9, verbose_name='состояние товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
