# Generated by Django 4.0.5 on 2022-07-29 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0002_advert_location_alter_advert_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='types_ad',
            field=models.CharField(blank=True, choices=[('куплю', 'куплю'), ('продам', 'продам'), ('обміняю', 'обміняю'), ('віддам', 'віддам'), ('аренда', 'аренда')], max_length=9, verbose_name='тип объявления'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
