# Generated by Django 4.0.5 on 2022-07-30 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0003_alter_advert_types_ad_alter_advert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(max_length=10000, verbose_name="Опис об'яви"),
        ),
        migrations.AlterField(
            model_name='advert',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='эл.почта'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ціна'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='types_ad',
            field=models.CharField(blank=True, choices=[('куплю', 'куплю'), ('продам', 'продам'), ('обміняю', 'обміняю'), ('віддам', 'віддам'), ('аренда', 'аренда')], max_length=9, verbose_name="тип об'яви"),
        ),
        migrations.AlterField(
            model_name='advert',
            name='types_pr',
            field=models.CharField(blank=True, choices=[('нове', 'нове'), ('подержане', 'подержане')], max_length=9, verbose_name='стан товару'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
