# Generated by Django 4.0.5 on 2022-08-17 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0006_alter_advert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ваше ім'я"),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='ціна'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
