# Generated by Django 4.0.5 on 2022-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_alter_advert_name_alter_advert_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ціна'),
        ),
    ]
