# Generated by Django 4.0.5 on 2022-10-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_alter_advert_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.category', verbose_name='Категорія*'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(max_length=10000, verbose_name="Опис об'яви*"),
        ),
        migrations.AlterField(
            model_name='advert',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Локація'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Ваше ім'я*"),
        ),
        migrations.AlterField(
            model_name='advert',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Назва*'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
